[project]
name = "mcp-calculate-server"
version = "1.0.0"
description = "计算器MCP服务,输入字符串的计算式，返回计算结果,更新信息：添加幂运算支持，放宽计算结果小数位数限制，并增强了错误处理能力。"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp>=1.12.3",
]
[project.scripts]
mcp-calculate-server = "main:main"
