[project]
name = "mcp-calculate-server"
version = "0.1.1"
description = "计算器MCP服务,输入字符串的计算式，返回计算结果"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp>=1.7.1",
]
[project.scripts]
mcp-calculate-server = "main:main"
